{% set name = "SpeechRecognition" %}
{% set version = "3.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Uberi/speech_recognition/archive/{{ version }}.tar.gz
  sha256: 01221e2ad4d1b76656082c0dd95c980b498cfa88c400595022c9aa3e1ae51e60
  patches:
    - libflac.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }},<3.13
    - libflac
    - requests
    - typing-extensions

test:
  imports:
    - speech_recognition
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/Uberi/speech_recognition
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: Library for performing speech recognition, with support for several engines and APIs, online and offline.
  dev_url: https://github.com/Uberi/speech_recognition

extra:
  recipe-maintainers:
    - CurtLH
    - jan-janssen
