{% set name = "SpeechRecognition" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Uberi/speech_recognition/archive/{{ version }}.tar.gz
  sha256: 7eae95e7030f99a6c63b4cc8d1e95f7716cb67979fc58de6f38731a71beb24dd
  patches:
    - libflac.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6,<3.13
    - pip
    - setuptools

  run:
    - python >=3.6,<3.13
    - libflac
    - requests
    - typing-extensions

test:
  imports:
    - speech_recognition
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Uberi/speech_recognition
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: Library for performing speech recognition, with support for several engines and APIs, online and offline.
  dev_url: https://github.com/Uberi/speech_recognition

extra:
  recipe-maintainers:
    - CurtLH
    - jan-janssen
