appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OFUm500YKZVhonjft3I0vfIboA3vzUScg9n3mZ3SY9m/LYqbtw+FGCA0DI4ektgw0I5hgNv3kTF5y628A2pZDM++febTDpDo35sRnLan8ppPWESsAgqLEZ53VhX9S1A8Rh6CSMNJbNo3MHjw3s0fT09bwS7whjHS6ee4jPpf+WusRxNL+3M/mOJUoxHp7kS17g4xeXnBMHztGqFlhFZY9feSiUwWB6WH8td1+e7WvxE9Rr0sIj1PFkfaa6vWHqDYmPhTmbbdAvMpmJMLM+QJTckOJrmc0qbYIv1B7oXTeqvFkxnzli6sLw+ruzU7qkHnolNSjdmI18NXZevpRFRA/xiBilwrqtyiu9Htr2jJKs7/a829vNmfuVcc5gL+sUdbffd2M1QvfTTyH+bxajgNaV1eIOF9vwT5ggwS62Dk3qxX2gJc9Y3mmNe8a9+OkB6fYWvEDI8zRQYUmw6qBG/MHSJupQcm1a0w3wuAwqCZ/AUEGlyJO8ZjLCqHHamJv7j0FJ4tjAXWR2rTQKTs6WSE1K94YNqUnNQRCzX4hAv/nbdw6Nb5XFfIEhr3gHMm5vt6yvejGTcoz8HBD8eFlKX7YDyX5gm7Voq45kRj2P8eXhWdarAt5picuRRd8oEGEkXtmElhdbeuOpR4+qEydPAzVloIPlRZLePBRSgSw18+WsA=}
